apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Access mode for the PVC    
  resources:
    requests:
      storage: 5Gi  # Requested storage size
