apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app      # Label selector for pods managed by this ReplicaSet
  template:
    metadata:
      name: java-container
      labels:
        app: java-app    # Labels applied to pods created by this ReplicaSet
    spec:
      containers:
        - name: java-container
          image: himalaya7087/java-image   # Replace with your Java application Docker image
          ports:
            - containerPort: 8080         # Port that your Java application listens on


